# Generated by Django 6.0.3 on 2026-03-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_d',
        ),
        migrations.AddField(
            model_name='question',
            name='option_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='1 balli javob'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='2 balli javob'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='3 balli javob'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='4 balli javob'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='5 balli javob'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.IntegerField(verbose_name="Umumiy to'plagan balli"),
        ),
    ]
