# Generated by Django 6.0.3 on 2026-03-14 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'Modul', 'verbose_name_plural': '7 ta Asosiy Modul'},
        ),
        migrations.RemoveField(
            model_name='module',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='module',
            name='file',
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Modul nomi (masalan: 1-Modul)'),
        ),
        migrations.CreateModel(
            name='ModuleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Blok nomi (Mavzu)')),
                ('file', models.FileField(upload_to='modules/blocks/', verbose_name='Word fayli')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.module', verbose_name='Qaysi modulga tegishli')),
            ],
            options={
                'verbose_name': 'Modul bloki',
                'verbose_name_plural': 'Modul bloklari',
            },
        ),
    ]
