# Generated by Django 6.0.3 on 2026-03-14 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'Modul', 'verbose_name_plural': '1. Asosiy Modullar'},
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Modul nomi'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Mavzu nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='main.module', verbose_name='Qaysi modulga tegishli')),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': '2. Mavzular',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Blok sarlavhasi (masalan: Kirish qismi)')),
                ('content', models.TextField(verbose_name='Asosiy matn/kontent')),
                ('file', models.FileField(blank=True, null=True, upload_to='modules/files/', verbose_name='Word fayli (ixtiyoriy)')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.topic', verbose_name='Qaysi mavzuga tegishli')),
            ],
            options={
                'verbose_name': 'Kontent bloki',
                'verbose_name_plural': '3. Mavzu bloklari',
            },
        ),
        migrations.DeleteModel(
            name='ModuleBlock',
        ),
    ]
